version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints:
          - node.role == manager

  65031141_ynu_nginx:
    image: nginx:latest
    restart: always
    volumes:
      - 65031141_volume:/usr/share/nginx:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=65031141.ynu.edu.cn
    deploy:
      placement:
        constraints:
          - node.role == manager

  65031141_ynu_gear:
    image: 65031141/65031141_ynu_gear
    restart: always
    volumes:
      - 65031141_volume:/root:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /root
    deploy:
      placement:
        constraints:
          - node.role == manager
    
  jump_ehall:
    image: nginx:latest
    restart: always
    volumes:
      - /opt/jump.ehall.ynu.edu.cn/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=jump.ehall.ynu.edu.cn
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  65031141_volume:
