# 采用traefik来做负载均衡，进而实现跨主机

version: '3'

services:
  # 65031141.ynu.edu.cn
  65031141_ynu_nginx:
    image: nginx:latest
    restart: always
    volumes:
      - 65031141_volume:/usr/share/nginx:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.frontend.rule=Host:65031141.ynu.edu.cn
      - label traefik.port=80
    networks:
      - portainer_agent_network
    deploy:
      placement:
        constraints:
          - node.role == manager

  65031141_ynu_gear:
    image: 65031141/65031141_ynu_gear:latest
    restart: always
    volumes:
      - 65031141_volume:/root:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - portainer_agent_network
    deploy:
      placement:
        constraints:
          - node.role == manager


  # jump.ehall.ynu.edu.cn
  jump_ehall:
    image: 65031141/jump_ehall:latest
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.frontend.rule=Host:jump.ehall.ynu.edu.cn
      - label traefik.port=80
    networks:
      - portainer_agent_network

volumes:
  65031141_volume: